### ISSUE TITLE
Сheck the arithmetic expression before interpreting it

### ISSUE THREAD

**Issue by EwanDubashinski** [EwanDubashinski/ci_test#1]
The application uses included JavaScript engine for interpreting an arithmetic expression. If some JS code will be put into the command line, the application will break.

`print('Hello, World');
Exception in thread "main" java.lang.NullPointerException
Hello, World 
	at Calc1.eval(Calc1.java:14)
	at Calc1.main(Calc1.java:25)`

Approved symbols:

- [x] 0123456789
- [x] +-/*
- [x] ()

**Comment by EwanDubashinski** [comment]
Implemented.
